// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vconfigurable_carry_select_adder.h for the primary calling header

#include "Vconfigurable_carry_select_adder__pch.h"
#include "Vconfigurable_carry_select_adder__Syms.h"
#include "Vconfigurable_carry_select_adder___024root.h"

#ifdef VL_DEBUG
VL_ATTR_COLD void Vconfigurable_carry_select_adder___024root___dump_triggers__stl(Vconfigurable_carry_select_adder___024root* vlSelf);
#endif  // VL_DEBUG

VL_ATTR_COLD void Vconfigurable_carry_select_adder___024root___eval_triggers__stl(Vconfigurable_carry_select_adder___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vconfigurable_carry_select_adder__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vconfigurable_carry_select_adder___024root___eval_triggers__stl\n"); );
    // Body
    vlSelf->__VstlTriggered.set(0U, (IData)(vlSelf->__VstlFirstIteration));
    vlSelf->__VstlTriggered.set(1U, ((IData)(vlSelf->configurable_carry_select_adder__DOT__block_carry) 
                                     != (IData)(vlSelf->__Vtrigprevexpr___TOP__configurable_carry_select_adder__DOT__block_carry__0)));
    vlSelf->__Vtrigprevexpr___TOP__configurable_carry_select_adder__DOT__block_carry__0 
        = vlSelf->configurable_carry_select_adder__DOT__block_carry;
    if (VL_UNLIKELY((1U & (~ (IData)(vlSelf->__VstlDidInit))))) {
        vlSelf->__VstlDidInit = 1U;
        vlSelf->__VstlTriggered.set(1U, 1U);
    }
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vconfigurable_carry_select_adder___024root___dump_triggers__stl(vlSelf);
    }
#endif
}

void Vconfigurable_carry_select_adder___024root___act_sequent__TOP__0(Vconfigurable_carry_select_adder___024root* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__1__KET____DOT__adder_0__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__1__KET____DOT__adder_1__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__2__KET____DOT__adder_0__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__2__KET____DOT__adder_1__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__3__KET____DOT__adder_0__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__3__KET____DOT__adder_1__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__4__KET____DOT__adder_0__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__4__KET____DOT__adder_1__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__5__KET____DOT__adder_0__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__5__KET____DOT__adder_1__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__6__KET____DOT__adder_0__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__6__KET____DOT__adder_1__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__7__KET____DOT__adder_0__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__7__KET____DOT__adder_1__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_comb__TOP__configurable_carry_select_adder__DOT__first_block__0(Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8* vlSelf);
void Vconfigurable_carry_select_adder___024root___ico_comb__TOP__0(Vconfigurable_carry_select_adder___024root* vlSelf);

VL_ATTR_COLD void Vconfigurable_carry_select_adder___024root___eval_stl(Vconfigurable_carry_select_adder___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vconfigurable_carry_select_adder__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vconfigurable_carry_select_adder___024root___eval_stl\n"); );
    // Body
    if ((2ULL & vlSelf->__VstlTriggered.word(0U))) {
        Vconfigurable_carry_select_adder___024root___act_sequent__TOP__0(vlSelf);
    }
    if ((1ULL & vlSelf->__VstlTriggered.word(0U))) {
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__1__KET____DOT__adder_0__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__1__KET____DOT__adder_0));
        vlSelf->__Vm_traceActivity[3U] = 1U;
        vlSelf->__Vm_traceActivity[2U] = 1U;
        vlSelf->__Vm_traceActivity[1U] = 1U;
        vlSelf->__Vm_traceActivity[0U] = 1U;
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__1__KET____DOT__adder_1__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__1__KET____DOT__adder_1));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__2__KET____DOT__adder_0__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__2__KET____DOT__adder_0));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__2__KET____DOT__adder_1__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__2__KET____DOT__adder_1));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__3__KET____DOT__adder_0__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__3__KET____DOT__adder_0));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__3__KET____DOT__adder_1__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__3__KET____DOT__adder_1));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__4__KET____DOT__adder_0__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__4__KET____DOT__adder_0));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__4__KET____DOT__adder_1__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__4__KET____DOT__adder_1));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__5__KET____DOT__adder_0__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__5__KET____DOT__adder_0));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__5__KET____DOT__adder_1__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__5__KET____DOT__adder_1));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__6__KET____DOT__adder_0__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__6__KET____DOT__adder_0));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__6__KET____DOT__adder_1__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__6__KET____DOT__adder_1));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__7__KET____DOT__adder_0__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__7__KET____DOT__adder_0));
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_sequent__TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__7__KET____DOT__adder_1__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__carry_select_blocks__BRA__7__KET____DOT__adder_1));
    }
    if ((3ULL & vlSelf->__VstlTriggered.word(0U))) {
        Vconfigurable_carry_select_adder_csa_ripple_carry_adder__W8___ico_comb__TOP__configurable_carry_select_adder__DOT__first_block__0((&vlSymsp->TOP__configurable_carry_select_adder__DOT__first_block));
        vlSelf->__Vm_traceActivity[3U] = 1U;
        vlSelf->__Vm_traceActivity[2U] = 1U;
        vlSelf->__Vm_traceActivity[1U] = 1U;
        vlSelf->__Vm_traceActivity[0U] = 1U;
        Vconfigurable_carry_select_adder___024root___ico_comb__TOP__0(vlSelf);
    }
}
