// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vparameterized_i2c_master.cpp"
#include "Vparameterized_i2c_master___024root__DepSet_h7bd98f3a__0.cpp"
#include "Vparameterized_i2c_master___024root__DepSet_h0353b3b2__0.cpp"
#include "Vparameterized_i2c_master__Trace__0.cpp"
#include "Vparameterized_i2c_master___024root__Slow.cpp"
#include "Vparameterized_i2c_master___024root__DepSet_h7bd98f3a__0__Slow.cpp"
#include "Vparameterized_i2c_master___024root__DepSet_h0353b3b2__0__Slow.cpp"
#include "Vparameterized_i2c_master__Syms.cpp"
#include "Vparameterized_i2c_master__Trace__0__Slow.cpp"
#include "Vparameterized_i2c_master__TraceDecls__0__Slow.cpp"
